/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function parseChatMessages(path: string): any
export function listGameEvents(path: string): any
export function parseGrenades(path: string): any
export function parseHeader(path: string): any
export function parseEvents(path: string, eventName: string, extraPlayer?: Array<string> | undefined | null, extraOther?: Array<string> | undefined | null): any
export function parseTicks(path: string, wantedProps: Array<string>): any
export function parsePlayerInfo(path: string): any
