/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function parseEvents(path: string, eventName: string, extraPlayer?: Array<string> | undefined | null, extraOther?: Array<string> | undefined | null): any
export function parseTicks(path: string, wantedProps: Array<string>): any
